spring:
  application:
    name: ENS-service

  profiles:
    active: default

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    config:
      fail-fast: true

  liquibase:
    change-log: db/changelog/changelog-master.xml

server:
  port: 0