spring:
  application:
    name: ens-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ENS
    username: postgres
    password: 9567
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  #  security:
  #    oauth2:
  #      resourceserver:
  #        jwt:
  #          issuer-uri: http://localhost:8080/realm/ENS
  #          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  profiles:
    active: default

  liquibase:
    change-log: db/changelog/changelog-master.xml

server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

jwt:
  auth:
    converter:
      resource-id: ENS-client
      principal-attribute: preferred_username