spring:
  application:
    name: ENS-gateway
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: account-service-route
          uri: lb://ens-service
          predicates:
            - Path=/accounts/**

        - id: notification-service-route
          uri: lb://ens-service
          predicates:
            - Path=/notification/**

server:
  port: 8765
  error:
    include-message: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"

