spring:
  application:
    name: ENS-gateway
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - TokenRelay=
      routes:
        - id: account-service-route
          uri: lb://ens-service
          predicates:
            - Path=/accounts/**

        - id: notification-service-route
          uri: lb://ens-service
          predicates:
            - Path=/notification/**
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/ENS
        registration:
          keycloak:
            provider: keycloak
            client-id: ENS-client
            client-secret: client-secret
            authorization-grant-type: authorization_code
            scope:
              - openid

server:
  port: 8765
  error:
    include-message: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"

